== 使用方法
=== ドキュメントの生成
NOTE: プロキシ環境下の場合は、事前に<<_gradleのプロキシ設定, Gradleのプロキシ設定>>をしてださい。

* プロジェクト直下で、下記を実行します。

[source, bash]
----
$ ./gradlew asciidoctor
----

* build/docs/asciidocフォルダ配下にHTMLとPDFが生成されます。``index.html``をブラウザで開くと生成されたHTMLが見れます。``index.pdf``をPDFビューワーで開くとPDFが見れます。
[source, bash]
----
$ tree /f build/docs/asciidoc
build/docs/asciidoc/
├── html5
│   ├── css
│   ├── images
│   ├── index.html
│   └── js
├── images
│   ├── github
│   │   ├── blockquote-arrow.png
│   │   └── li-chevron.png
│   ├── golo
│   │   ├── body-bg.png
│   │   └── pre-bg.png
│   ├── maker
│   │   └── body-bg.png
│   └── riak
│       ├── body-bg.jpg
│       ├── footer-bg.jpg
│       ├── info-bg.jpg
│       ├── pre-bg.jpg
│       └── sidebar-bg.jpg
└── pdf
    ├── css
    ├── images
    ├── index.pdf
    └── js
----


=== ライブリロードを使う場合
adocファイルを修正するとHTMLを出力し、
ブラウザに修正がリアルタイムに反映されるようにします。

==== 手順
* プロジェクト直下で下記を実行します。

[source, bash]
----
$ ./gradlew -t asciidoctor
----

* もう一つ別のコマンドプロンプト(またはターミナル)を起動し、プロジェクト直下で下記を実行します。

[source, bash]
----
$ ./gradlew liveReload
----

* Chromeで http://localhost:35729/html5/ を開きます。

* ChromeのLiveReload機能をONにします。（右上にあるLiveReloadアイコンをクリックします）

* この状態でadocファイルを編集するとブラウザに編集内容がリアルタイムに反映されます。


== Gradleのプロキシ設定
* プロジェクト直下の``gradle.properties``を編集します。

.gradle.properties
[source]
----
######################################
# gradlew実行時のプロキシ設定
######################################
# http
#systemProp.http.proxyHost = [your proxy host]   // <1>
#systemProp.http.proxyPort = [your proxy port]   // <2>
#systemProp.http.proxyUser = [your proxy user]   // <3>
#systemProp.http.proxyPassword = [your proxy password]   // <4>
#systemProp.http.nonProxyHosts = localhost   // <5>

# https    // <6>
#systemProp.https.proxyHost = [your proxy host]
#systemProp.https.proxyPort = [your proxy port]
#systemProp.https.proxyUser = [your proxy user]
#systemProp.https.proxyPassword = [your proxy password]
#systemProp.https.nonProxyHosts = localhost

org.gradle.jvmargs = -Dfile.encoding=UTF-8
org.gradle.daemon = true
#org.gradle.java.home = [JDK install dir path]
----
<1> コメントアウトしてプロキシのホストを指定します。
<1> コメントアウトしてプロキシのポートを指定します。
<3> 認証が必要であれば、コメントアウトしてユーザ名を指定します。
<4> 認証が必要であれば、コメントアウトしてパスワードを指定します。
<5> プロキシ除外対象のホストがあれば``|``区切りで指定します。
<6> httpsも同様に設定が必要であればコメントアウトして、それぞれ値を指定します。




